# -*- coding: utf-8 -*-
"""sentiment_analysis Cluster 3-Oppo & Samsung.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ikDxRFFdRJssW_uQLmth972Eape5f_lc
"""

!pip install scikit-plot
!pip install afinn
!pip install newspaper3k

#imports
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import scikitplot as skplot


from wordcloud import WordCloud
import re

# text imports

import spacy
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer,TfidfVectorizer  
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
from afinn import Afinn
from newspaper import Article
from textblob import TextBlob

#Oppo A53
op_URL = 'https://www.techradar.com/sg/reviews/phones/mobile-phones/nexus-6p-1305318/review'
article = Article(op_URL)
article.download()
article.parse()
wc = WordCloud(background_color="white")
wordcloud = wc.generate(article.text)

# # Display the  plot:
plt.imshow(wordcloud)
plt.axis("off")
plt.show()

text = article.text.replace('\n', '')
one_sentences = text.split('.')

def polarity_score(text):
    p = TextBlob(text).sentiment.polarity
    return p

def subjectivity_score(text):
    s = TextBlob(text).sentiment.subjectivity
    return s

def sent_score(text):
    afinn=Afinn()
    return afinn.score(text)

#Calculate Scores and complie them in a df
def calculate_scores(df):
    df = df.copy(deep = True)
    
    df['polarity'] = df.Sentences.apply(polarity_score)

    df['subjectivity'] = df.Sentences.apply(subjectivity_score)

    df['sent'] = df.Sentences.apply(sent_score)
    return df

opp_df = pd.DataFrame({'Sentences' : one_sentences, 'Model' : 'Oppo A53 X', 'Label' : '0'} )

opp_df['polarity'] = opp_df.Sentences.apply(polarity_score)

opp_df['subjectivity'] = opp_df.Sentences.apply(subjectivity_score)

opp_df['sent'] = opp_df.Sentences.apply(sent_score)

opp_df.plot.scatter('polarity', 'subjectivity')
plt.show()

sns.lmplot('polarity', 'sent', data = opp_df)
plt.show()

#Samsung Galaxy A8

sam_URL = 'https://www.techradar.com/sg/reviews/samsung-galaxy-a8-review'
article2 = Article(sam_URL)
article2.download()
article2.parse()
wcd = WordCloud(background_color="white")
wordcloud2 = wc.generate(article2.text)

# # Display the  plot:
plt.imshow(wordcloud2)
plt.axis("off")
plt.show()

text = article2.text.replace('\n', '')
sam_sentences = text.split('.')

sam_df = pd.DataFrame({'Sentences' : sam_sentences, 'Model' : 'Huawei Nexus 6P 2', 'Label' : '0'} )

sam_df = calculate_scores(sam_df)

sam_df.plot.scatter('polarity', 'subjectivity')
plt.show()

sns.lmplot('polarity', 'sent', data = sam_df)
plt.show()
opp_df = opp_df.append(sam_df)

opp_df.groupby('Model').mean()











